Первая рабочая версия телеграмм-бота, помогающего при составлении списка покупок
NikitaTiv/ShoppingBot pull request #16
Opened 2023-01-12 19:08 UTC by Vladislav-opto

Работа через базу данных.
Есть README

2023-01-13 18:25 UTC, Melevir requested changes

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/bot.py
> +sys.path.insert(1, os.path.join(sys.path[0], '..'))
Э не, от этого надо избавиться. Самый простой способ – перетащить главный файл, который ты запускаешь, на уровень выше, в корневую директорию.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/dialog.py
> +        return ConversationHandler.END
Этот ретурн можно не дублировать, а написать после ифа.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/dialog.py
> +    goods_str = "\n".join(map(str, get_all_goods()))
Вкусовщина, но я вместо map советую использовать компрехеншен.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/handlers.py
> +from utils import main_keyboard, get_smile, play_random_numbers
У тебя есть файл dialog.py, в котором живут хендлеры и handlers.py, в котором тоже живут хендлеры. Не до конца догоняю, в чём разница.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/handlers.py
> +            user_number = int(context.args[0])
Тут бы предусмотреть случай того, что пользватель написал какую-то ерунду.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/handlers.py
> +from utils import main_keyboard, get_smile, play_random_numbers
А ещё кажется, что в этом файле есть хендлеры, которые вообще не используются в проекте.

Эксперименты – это хорошо, но в репо им делать нечего раз они к проекту не относятся.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/bot/utils.py
> +sys.path.insert(1, os.path.join(sys.path[0], '..'))
Тоже лишнее.

Вот моя старая статья об этом, мб поможет: https://melevir.medium.com/%D0%BA%D0%BE%D1%80%D0%BE%D1%87%D0%B5-%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D1%8F-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D1%8B-%D0%B2-python-e8e024f2730a

Если нет – скажи, в одну из оставшихся суббот расскажу/покажу.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/db/CRUD.py
> +    Good.query.delete()
Ето очень опасно, в реальности велик риск дропнуть лишнее. Лучше сделай удаление всех записей для конкретного пользователя.

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/db/db.py
> +sys.path.insert(1, os.path.join(sys.path[0], '..'))
ну и тут тоже лишнее

2023-01-13 18:25 UTC, Melevir commented on shopping_manager_bot/settings/settings_file.py
> +API_KEY = '5941807026:AAHmB8Afi3zf7inQd00zUwtLD003MEL7Ozg'
Кажется, этот файл должен быть секретным и отсутсвовать в репо :)

Удали его и добавь название в гитигнор чтобы больше не повторять.

2023-01-16 18:30 UTC, Vladislav-opto commented on shopping_manager_bot/bot/bot.py
> +sys.path.insert(1, os.path.join(sys.path[0], '..'))
Исправил.

2023-01-16 18:34 UTC, Vladislav-opto commented on shopping_manager_bot/bot/handlers.py
> +from utils import main_keyboard, get_smile, play_random_numbers
Исправлено.

2023-01-17 06:28 UTC, Melevir commented on shopping_manager_bot/README.md
> +5. Впишите в settings.py переменные:
Давай теперь через переменные окружения :)

2023-01-17 06:28 UTC, Melevir commented on shopping_manager_bot/bot/bot.py
> +
Тут и в некоторых других местах не хватает пустой строки.

2023-01-17 06:28 UTC, Melevir commented on shopping_manager_bot/bot/handlers.py
> +    context.user_data['emoji'] = get_smile(context.user_data)
Не догоняю, зачем класть смайлик в юзер дату, он ж не нужен нигде, кроме этой вьюхи.

2023-01-17 06:28 UTC, Melevir commented on shopping_manager_bot/bot/utils.py
> +def get_smile(user_data: dict) -> str:
С учётом комментария выше, кажется, что это функцию можно упростить до вызова choice.

2023-01-17 06:28 UTC, Melevir commented on shopping_manager_bot/db/CRUD.py
> +    result = Good.query.with_entities(Good.id).filter(Good.user_id == user_id).all()
Сделай тогда тут прям запрос delete: https://docs.sqlalchemy.org/en/20/tutorial/data_update.html#the-delete-sql-expression-construct

2023-01-19 05:32 UTC, Melevir approved these changes

2023-01-19 05:32 UTC, Melevir commented on shopping_manager_bot/bot/handlers.py
> +    #context.bot.send_message(783186475, update.message.text, reply_markup=main_keyboard())  - на данный момент это тестовая функция, удалять не буду при пуше :)
И принт и коммент удалить бы.

2023-01-19 05:32 UTC, Melevir commented on shopping_manager_bot/db/CRUD.py
> +            delete_stmt = sqlalchemy.delete(Good).where(Good.id == good_id[0]) #Илья, я исправил, но проще и понятнее это не выглядит :(
Не выглядит проще и понятнее потому что ты первый раз сталкиваешься с этим. На деле это более логичный и эффективный способ :)

2023-01-19 18:41 UTC, merged