Feature/vpl
NikitaTiv/ShoppingBot pull request #4
Opened 2022-12-12 06:07 UTC by Vladislav-opto

2022-12-12 06:55 UTC, Melevir requested changes
requirements.txt стоит добавить, просто не в директорию с кодом, а в корень проекта.

Тексты к коммитам стали осмысленее, но договоритесь о языке, на котором вы их пишите и пишите все на одном.

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_category: io.TextIOWrapper, input_check: io.TextIOWrapper) -> None:
`input_category` и `input_check` – это строки. Аннотацию поправить бы.

Функция делает сразу три вещи: считывает данные, обрабатывает и сохраняет. Каждый из этих этапов вытащить бы в отдельную функцию.

И смысл того, что делает функция, непонятен: берёт один джейсон, перекладывает в другой... докстрингу добавить бы.

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +        key_name = good.get("name", "пусто").replace(".", " ").replace(",", " ").replace("/", " ")
`пусто` должен быть `None`

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +    with open("verified_check_with_categories.json", "w", encoding='utf-8') as write_file:
Входные файлы приходят аргументом, а выходной почему-то захардкожен.

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_category: io.TextIOWrapper, input_check: io.TextIOWrapper) -> None:
Ага, ты тут категорию добавляешь, допёр. Если разбить на функции, должно быть понятнее.

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +                    check_verified[number]["category"] = category
Не хватает break.

2022-12-12 06:55 UTC, Melevir commented on categorization/categorization.py
> +        for category in categories:
По-хорошему мы для каждой позиции в чеке должны определять категорию, а если её нет – хотя бы сообщать об этом. Используй модуль logging для этого.

2022-12-12 06:55 UTC, Melevir commented on qr_code_scan_opencv/QR_to_string_openCV.py
> +        return "Не удалось распознать QR-код! Повторите попытку!"
Сообщения ошибок следует пихать не в ретурн, а у исключения, которое тут хорошо бы выкилывать.

2022-12-12 06:55 UTC, Melevir commented on qr_code_scan_opencv/QR_to_string_openCV.py
> +def read_qr_code(filename: str) -> str: #принимает на вход путь до файла вместе с его расширением
Если принимает на вход путь, а не имя файла, то это filepath, а не filename.

2022-12-12 07:51 UTC, Vladislav-opto commented on categorization/categorization.py
> +        key_name = good.get("name", "пусто").replace(".", " ").replace(",", " ").replace("/", " ")
Тогда перестанет работать replace.

2022-12-12 07:51 UTC, Vladislav-opto commented on categorization/categorization.py
> +                    check_verified[number]["category"] = category
Тогда он не добавит категории.

2022-12-12 07:51 UTC, Vladislav-opto commented on categorization/categorization.py
> +        for category in categories:
Вывожу вместо этого в категорию - "Не определена"

2022-12-12 07:52 UTC, Melevir commented on categorization/categorization.py
> +        key_name = good.get("name", "пусто").replace(".", " ").replace(",", " ").replace("/", " ")
Так перепиши код так, чтобы этот случай семантично обрабатывался без ошибок :)

2022-12-12 07:53 UTC, Melevir commented on categorization/categorization.py
> +                    check_verified[number]["category"] = category
Так декомпозируй код так, чтобы всё было понятно, логично и без лишних прогонов циклов :)

2022-12-12 07:53 UTC, Melevir commented on categorization/categorization.py
> +        for category in categories:
Абсолютно неочевидно из кода.

2022-12-12 10:19 UTC, Melevir requested changes
Попробуй запускать mypy на своём коде. Сперва станет большнее, но со временем ошибок будет куда меньше.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +def read_from_json(input_file: io.TextIOWrapper) -> str:
Эта и следующая функция не имеет отношения к категоризации, она общая, поэтому ей не место в этом файле и этом модуле.

И аннотация аргумента тут неправильная.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_categories: str, check: str) -> str:
Эта функция не добавляет категорию в файл. Она вообще ничего не знает про файлы.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_categories: str, check: str) -> str:
А ещё тут неправильные аннотации и для аргументов и для возвращаемого значения.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +        if "name" in good:
Если тебе точно нужен этот иф, то сделай так: `if 'name' not in good: continue`

Тогда остальной код можно будет писать без отступа.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +    for number, good in enumerate(check):
Попробуй найти способ избавиться от необходимости обращаться к элементу по списку. Тогда и переменная number не нужна будет.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +            result_category = "не определена"
Если категория не определилась, то категоризатор должен возвращать None.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +            key_name = good["name"].replace(".", " ").replace(",", " ").replace("/", " ")
key_name переименовать бы.

Ну и логику определения категории я бы вынес в отдельную фунцию.

2022-12-12 10:19 UTC, Melevir commented on categorization/categorization.py
> +                for word in good_as_list:
Почитай про метод intersection у set и попрбуй упростить этот код.

2022-12-13 20:16 UTC, Vladislav-opto commented on categorization/categorization.py
> +def read_from_json(input_file: io.TextIOWrapper) -> str:
Ты изначально попросил вынести в отдельную функцию работу с json.
Теперь говоришь, что этим функциям тут нет места...
Не до конца понимаю, что ты тут предлагаешь поменять.
Вынести работу json в отдельный файл?

2022-12-13 20:19 UTC, Vladislav-opto commented on categorization/categorization.py
> +def add_categories_to_file(input_categories: str, check: str) -> str:
Изменил название на add_categories_to_check - так норм?
Запустил с reveal_type - везде должны быть str.

2022-12-14 05:41 UTC, Melevir commented on categorization/categorization.py
> +def read_from_json(input_file: io.TextIOWrapper) -> str:
Да. Сначала я просил вынести работа с json в отдельные функции, теперь прошу положить эти функции куда надо. 

Этот модуль называется categorization, соответсвенно я ожидаю, что в нём живёт всё, связанное с категоризацией. Загрузка и сохранение файлов к категоризации отношения не имеют.

2022-12-14 05:43 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_categories: str, check: str) -> str:
Лучше, но не достаточно хорошо. Вообще, "check" – это "проверка". "Чек" – это "receipt".

2022-12-14 05:43 UTC, Melevir commented on categorization/categorization.py
> +def add_categories_to_file(input_categories: str, check: str) -> str:
Ну и аннотация тут неверная. Если reveal_type тебе говорит обратное, значит ты им неправильно воспользовался :)

2022-12-15 04:51 UTC, Melevir requested changes
requirements.txt всё ещё нет, mypy на своём коде так и не запускал. Очень советую ;)

2022-12-15 04:51 UTC, Melevir commented on categorization/categorization.py
> +def category_definition(input_categories: str, good: str) -> Union[str, None]:
Функция что-то делает, поэтому в названии функции всегда должен быть глагол. Не "определение", а "определить".

2022-12-15 04:51 UTC, Melevir commented on categorization/categorization.py
> +def category_definition(input_categories: str, good: str) -> Union[str, None]:
Аннотации аргументов всё ещё неверные.

Аннотация возвращаемого значения в современном питоне пишется как `str | None`

2022-12-15 04:51 UTC, Melevir commented on categorization/categorization.py
> +    for category in input_categories:
Тут в цикле тебе нужен и ключ словаря и его значение. Попробуй использовать метод items вместо того, чтобы делать `input_category[category]`.

2022-12-15 04:51 UTC, Melevir commented on categorization/categorization.py
> +        if 'name' not in good: continue
`continue` должен быть на новой строке и с отступом.

2022-12-15 04:51 UTC, Melevir commented on categorization/categorization.py
> +        if 'name' not in good: continue
А ещё этого ифа не должно существовать: у каждой строки чека должно быть название.

2022-12-15 04:51 UTC, Melevir commented on categorization/json_func.py
> +import json
Стало лучше, но ты всё равно положил этот файл в модуль categorization, а он не имеет к этому модулю отношения.

Обычно для таких функций создают модуль utils. Я бы положил этот код в `utils/json_tools.py`

2022-12-15 04:51 UTC, Melevir commented on categorization/json_func.py
> +def read(input_file: str) -> str:
Эта функция на вход принимает не файл, а путь до файла.

И возвращает не строку.

2022-12-15 04:51 UTC, Melevir commented on categorization/json_func.py
> +def write(output_file: str, data_to_write: str) -> None:
Эта функция принимает на вход не output_file, а путь до него.

И data_to_write – это не строка.

2022-12-15 19:59 UTC, Vladislav-opto commented on categorization/json_func.py
> +def read(input_file: str) -> str:
Название аргумента исправил. Аннотация возвращаемого значения теперь list.

2022-12-15 20:01 UTC, Vladislav-opto commented on categorization/json_func.py
> +def write(output_file: str, data_to_write: str) -> None:
Название аргумента исправил.
Не строка, а лист - исправил.

2022-12-15 20:02 UTC, Vladislav-opto commented on categorization/categorization.py
> +        if 'name' not in good: continue
continue  перенес.
А вот с ифом - пока оставлю, ибо Саша пока не прислал пример формат своего исправленного файла.

2022-12-15 20:02 UTC, Vladislav-opto commented on categorization/categorization.py
> +def category_definition(input_categories: str, good: str) -> Union[str, None]:
Название функции поправил.

2022-12-15 20:03 UTC, Vladislav-opto commented on categorization/categorization.py
> +def category_definition(input_categories: str, good: str) -> Union[str, None]:
requirements.txt сгенерил - лежит в корне проекта.

2022-12-15 20:10 UTC, Vladislav-opto commented on categorization/categorization.py
> +def category_definition(input_categories: str, good: str) -> Union[str, None]:
Аннотации аргументов поправил.

2022-12-15 20:26 UTC, Vladislav-opto commented on categorization/categorization.py
> +    for category in input_categories:
Исправил.

2022-12-16 07:45 UTC, Melevir commented on categorization/categorization.py
> +sys.path.append("../utils/")
Чтобы такого не делать, надо файл, который ты запускаешь из консоли, поместить в корень репозитория. Тогда ты сможешь в нём сделать `from utils import json_func`.

А вот моя заметка о том, как работают импорты в Питоне: https://melevir.medium.com/%D0%BA%D0%BE%D1%80%D0%BE%D1%87%D0%B5-%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D1%8F-%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D1%8B-%D0%B2-python-e8e024f2730a

2022-12-16 07:45 UTC, Melevir commented on categorization/categorization.py
> +    for category in tuple_categories:
Чтобы в коде не делать `category[0]` и `category[1]`, ты можешь сделать этот трюк прямо тут: `for category_name, category_words in tuple_categories`.

Переменную `tuple_categories ` я бы тоже не стал создавать, получилось бы `for category_name, category_words in input_categories.items():`.

2022-12-16 07:45 UTC, Melevir commented on categorization/categorization.py
> +        if 'name' not in good:
Всё ещё не понимаю, зачем этот иф. Или избавься от него или сделай так, чтобы при чтении кода было понятно, зачем он нужен.

2022-12-21 08:17 UTC, Melevir commented on categorization/categorization.py
> +def define_category(input_categories: dict, good: dict) -> str | None:
input_categories я бы переименовал в какой-нибудь categories_corpus, чтобы было понятно, что это не входные категории (из чеков), а именно данные для определения категории.

2022-12-21 08:17 UTC, Melevir commented on categorization/categorization.py
> +    for category_name, category_words in input_categories.items():
Смари как тут можно оптимизировать.

Представь, что проект развивается и категорий стало в 100 раз больше. Тогда определение категории будет занимать в ~100 раз больше времени.

А вот если ты переделаешь на цикл по good_as_list, а input_categories превратишь в маппинг из слова-триггера в категорию, то можно будет справиться сильно быстрее при большом количестве категорий.

Это опциональная оптимизация, можно её не делать, пишу для общего развития :)

2022-12-21 08:17 UTC, Melevir commented on database/CRUD_user.py
> +from db import db_session
Эээ, а почему в одном пул-реквесте и старое определение категорий и новая работа с БД? Не порядок. БД должна быть в новом пр, категоризатора в нём быть не должно.

2022-12-21 08:17 UTC, Melevir commented on database/CRUD_user.py
> +    user = User(name=input_name, name_photo=input_name_photo, date_upload = datetime.datetime.now())
Ты перепутал с моделями слегка. Пользователь - это пользователь, а чек - это чек, это отдельные сущности.

У чека должна быть инфа о том, какой пользователь загрузил этот чек, но это разные таблицы.

2022-12-21 08:17 UTC, Melevir commented on database/CRUD_user.py
> +def get_user_info(input_id: int) -> str:
Тут опять смешано получение и репрезентация данных. Принимай на вход айди пользователя и возвращай объект пользователя (или список его чеков).

2022-12-21 08:17 UTC, Melevir commented on database/models.py
> +class User(Base):
Выше я уже написал, что структуру БД надо доработать: разделить пользователей и чеки.

Вот туториал: https://hackersandslackers.com/sqlalchemy-data-models/

В нём есть пользователи, посты и комментарии к постам. У тебя вместо постов чеки, а вместо комментариев – позиции в чеке.

2022-12-23 05:33 UTC, Melevir approved these changes

2022-12-23 08:07 UTC, merged